<?php

namespace Database\Seeders;

use App\Models\Color;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ColorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $colors = array(
            array('IndianRed', '#CD5C5C'),
            array('LightCoral', '#F08080'),
            array('Salmon', '#FA8072'),
            array('DarkSalmon', '#E9967A'),
            array('LightSalmon', '#FFA07A'),
            array('Crimson', '#DC143C'),
            array('Red', '#FF0000'),
            array('FireBrick', '#B22222'),
            array('DarkRed', '#8B0000'),
            array('Pink', '#FFC0CB'),
            array('LightPink', '#FFB6C1'),
            array('HotPink', '#FF69B4'),
            array('DeepPink', '#FF1493'),
            array('MediumVioletRed', '#C71585'),
            array('PaleVioletRed', '#DB7093'),
            array('LightSalmon', '#FFA07A'),
            array('Coral', '#FF7F50'),
            array('Tomato', '#FF6347'),
            array('OrangeRed', '#FF4500'),
            array('DarkOrange', '#FF8C00'),
            array('Orange', '#FFA500'),
            array('Gold', '#FFD700'),
            array('Yellow', '#FFFF00'),
            array('LightYellow', '#FFFFE0'),
            array('LemonChiffon', '#FFFACD'),
            array('LightGoldenrodYellow', '#FAFAD2'),
            array('PapayaWhip', '#FFEFD5'),
            array('Moccasin', '#FFE4B5'),
            array('PeachPuff', '#FFDAB9'),
            array('PaleGoldenrod', '#EEE8AA'),
            array('Khaki', '#F0E68C'),
            array('DarkKhaki', '#BDB76B'),
            array('Lavender', '#E6E6FA'),
            array('Thistle', '#D8BFD8'),
            array('Plum', '#DDA0DD'),
            array('Violet', '#EE82EE'),
            array('Orchid', '#DA70D6'),
            array('Fuchsia', '#FF00FF'),
            array('Magenta', '#FF00FF'),
            array('MediumOrchid', '#BA55D3'),
            array('MediumPurple', '#9370DB'),
            array('Amethyst', '#9966CC'),
            array('BlueViolet', '#8A2BE2'),
            array('DarkViolet', '#9400D3'),
            array('DarkOrchid', '#9932CC'),
            array('DarkMagenta', '#8B008B'),
            array('Purple', '#800080'),
            array('Indigo', '#4B0082'),
            array('SlateBlue', '#6A5ACD'),
            array('DarkSlateBlue', '#483D8B'),
            array('MediumSlateBlue', '#7B68EE'),
            array('GreenYellow', '#ADFF2F'),
            array('Chartreuse', '#7FFF00'),
            array('LawnGreen', '#7CFC00'),
            array('Lime', '#00FF00'),
            array('LimeGreen', '#32CD32'),
            array('PaleGreen', '#98FB98'),
            array('LightGreen', '#90EE90'),
            array('MediumSpringGreen', '#00FA9A'),
            array('SpringGreen', '#00FF7F'),
            array('MediumSeaGreen', '#3CB371'),
            array('SeaGreen', '#2E8B57'),
            array('ForestGreen', '#228B22'),
            array('Green', '#008000'),
            array('DarkGreen', '#006400'),
            array('YellowGreen', '#9ACD32'),
            array('OliveDrab', '#6B8E23'),
            array('Olive', '#808000'),
            array('DarkOliveGreen', '#556B2F'),
            array('MediumAquamarine', '#66CDAA'),
            array('DarkSeaGreen', '#8FBC8F'),
            array('LightSeaGreen', '#20B2AA'),
            array('DarkCyan', '#008B8B'),
            array('Teal', '#008080'),
            array('Aqua', '#00FFFF'),
            array('Cyan', '#00FFFF'),
            array('LightCyan', '#E0FFFF'),
            array('PaleTurquoise', '#AFEEEE'),
            array('Aquamarine', '#7FFFD4'),
            array('Turquoise', '#40E0D0'),
            array('MediumTurquoise', '#48D1CC'),
            array('DarkTurquoise', '#00CED1'),
            array('CadetBlue', '#5F9EA0'),
            array('SteelBlue', '#4682B4'),
            array('LightSteelBlue', '#B0C4DE'),
            array('PowderBlue', '#B0E0E6'),
            array('LightBlue', '#ADD8E6'),
            array('SkyBlue', '#87CEEB'),
            array('LightSkyBlue', '#87CEFA'),
            array('DeepSkyBlue', '#00BFFF'),
            array('DodgerBlue', '#1E90FF'),
            array('CornflowerBlue', '#6495ED'),
            array('MediumSlateBlue', '#7B68EE'),
            array('RoyalBlue', '#4169E1'),
            array('Blue', '#ff0000'),
            array('MediumBlue', '#0000CD'),
            array('DarkBlue', '#00008B'),
            array('Navy', '#000080'),
            array('MidnightBlue', '#191970'),
            array('Cornsilk', '#FFF8DC'),
            array('BlanchedAlmond', '#FFEBCD'),
            array('Bisque', '#FFE4C4'),
            array('NavajoWhite', '#FFDEAD'),
            array('Wheat', '#F5DEB3'),
            array('BurlyWood', '#DEB887'),
            array('Tan', '#D2B48C'),
            array('RosyBrown', '#BC8F8F'),
            array('SandyBrown', '#F4A460'),
            array('Goldenrod', '#DAA520'),
            array('DarkGoldenrod', '#B8860B'),
            array('Peru', '#CD853F'),
            array('Chocolate', '#D2691E'),
            array('SaddleBrown', '#8B4513'),
            array('Sienna', '#A0522D'),
            array('Brown', '#A52A2A'),
            array('Maroon', '#800000'),
            array('White', '#FFFFFF'),
            array('Snow', '#FFFAFA'),
            array('Honeydew', '#F0FFF0'),
            array('MintCream', '#F5FFFA'),
            array('Azure', '#F0FFFF'),
            array('AliceBlue', '#F0F8FF'),
            array('GhostWhite', '#F8F8FF'),
            array('WhiteSmoke', '#F5F5F5'),
            array('Seashell', '#FFF5EE'),
            array('Beige', '#F5F5DC'),
            array('OldLace', '#FDF5E6'),
            array('FloralWhite', '#FFFAF0'),
            array('Ivory', '#FFFFF0'),
            array('AntiqueWhite', '#FAEBD7'),
            array('Linen', '#FAF0E6'),
            array('LavenderBlush', '#FFF0F5'),
            array('MistyRose', '#FFE4E1'),
            array('Gainsboro', '#DCDCDC'),
            array('LightGrey', '#D3D3D3'),
            array('Silver', '#C0C0C0'),
            array('DarkGray', '#A9A9A9'),
            array('Gray', '#808080'),
            array('DimGray', '#696969'),
            array('LightSlateGray', '#778899'),
            array('SlateGray', '#708090'),
            array('DarkSlateGray', '#2F4F4F'),
            array('Black', '#000000'),
            array('Light Claret Red', '#696969'),
            array('Light Grey', '#778899'),
            array('Tile Red', '#708090'),
            array('Saxe Blue', '#696969'),
            array('Navy Blue', '#778899'),
            array('Multi-Color', '#696969'),
            array('Grey', '#778899'),
            array('Powder', '#708090')
        );
        foreach ($colors as $color) {
            Color::withTrashed()->updateOrCreate([
                'code' => $color[1]
            ],[
                'name' => $color[0],
                'code' => $color[1]
            ]);
        }
    }
}
